name: 'Build'

on:
  - push
  - pull_request

jobs:
    linux:
        strategy:
            fail-fast: false
            matrix:
                include:
                  - name: SDL 2
                    flags: '-DREMCPE_PLATFORM=sdl2'
                    packages: 'libsdl2-dev'
                  - name: SDL 1.2
                    flags: '-DREMCPE_PLATFORM=sdl1'
                    packages: 'libsdl1.2-dev'
        name: Linux (${{ matrix.name }})
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
            with:
                submodules: true
          - name: Install Dependencies
            run: |
                sudo apt-get update
                sudo apt-get install --no-install-recommends -y \
                    build-essential \
                    cmake ninja-build \
                    libopenal-dev \
                    zlib1g-dev \
                    ${{ matrix.packages }}
          - name: Build
            run: |
                mkdir build
                cd build
                cmake -GNinja ${{ matrix.flags }} ..
                cmake --build .
    wasm:
        name: WASM
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
            with:
                submodules: true
          - name: Install Dependencies
            run: |
                sudo apt-get update
                sudo apt-get install --no-install-recommends -y cmake ninja-build
          - name: Build
            run: ./build-wasm.sh
    macos:
        strategy:
            fail-fast: false
            matrix:
                include:
                  - name: SDL 2
                    backend_name: 'SDL2'
                    packages: 'libsdl2'
                  # @NOTE: Uses SDL 1.2 compatibility layer in newer macOS versions, resulting in 30+ minutes spent building
                  # and installing said layer each time the action is run. We're not doing that.
                  #- name: SDL 1.2
                  #  backend_name: 'SDL1'
                  #  packages: 'libsdl'
        name: macOS (${{ matrix.name }})
        runs-on: macos-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
            with:
                submodules: true
          - name: Install MacPorts
            uses: melusina-org/setup-macports@v1
          - name: Install Dependencies
            run: |
                port selfupdate
                port install ${{ matrix.packages }} +universal
          - name: Build macOS Archive
            run: |
                cd platforms/macos/projects/Minecraft
                xcodebuild -scheme "MinecraftClient.${{ matrix.backend_name }}" \
                -archivePath $RUNNER_TEMP/GitHubActions_MacOS_${{ matrix.backend_name }}.xcarchive \
                -sdk macosx \
                -configuration "Release [${{ matrix.backend_name }}] (Default)" \
                -destination generic/platform=macOS \
                GCC_PREPROCESSOR_DEFINITIONS='$(GCC_PREPROCESSOR_DEFINITIONS)' \
                -quiet \
                clean archive 
    # @NOTE: Newer versions of Xcode will complain and refuse to build old XIB files or target old iOS versions
    #ios:
    #    runs-on: macos-latest
    #    steps:
    #      - name: Checkout Repository
    #        uses: actions/checkout@v3
    #        with:
    #            submodules: true
    #      - name: Build iOS Archive
    #        run: |
    #            cd platforms/macos/projects/Minecraft
    #            xcodebuild -scheme "minecraftpe" \
    #            -archivePath $RUNNER_TEMP/GitHubActions_iOS.xcarchive \
    #            -sdk iphoneos \
    #            -configuration "Release [iOS] (Default)" \
    #            -destination generic/platform=iOS \
    #            GCC_PREPROCESSOR_DEFINITIONS='$(GCC_PREPROCESSOR_DEFINITIONS)' \
    #            -quiet \
    #            clean archive 
    android:
        strategy:
            fail-fast: false
            matrix:
                include:
                  - name: SDL 2
                    directory: platforms/sdl/sdl2/android
                  - name: Native
                    directory: platforms/android/project
        name: Android (${{ matrix.name }})
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
            with:
                submodules: true
          - name: Setup JDK
            uses: actions/setup-java@v4
            with:
                java-version: '17'
                distribution: 'temurin'
                cache: gradle
          - name: Build
            run: |
                cd ${{ matrix.directory }}
                ./gradlew build
    mingw:
        strategy:
            fail-fast: false
            matrix:
                include:
                  - name: Win32
                    flags: '-DREMCPE_PLATFORM=windows'
                  - name: SDL2
                    flags: "-DREMCPE_PLATFORM=sdl2"
                  # CMake can't find it
                  #- name: SDL 1.2
                  #  flags: "-DREMCPE_PLATFORM=sdl1"
        name: MinGW-w64 (${{ matrix.name }})
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
            with:
                submodules: true
          - name: Install Dependencies
            run: |
                sudo apt-get update
                sudo apt-get install --no-install-recommends -y \
                    build-essential \
                    cmake ninja-build \
                    mingw-w64
          - name: Build
            run: |
                mkdir build
                cd build
                cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=../cmake/mingw-w64-toolchain.cmake ${{ matrix.flags }} ..
                cmake --build .
